### PR TITLE
Markets: populate data

### LINKED ISSUE #155: Markets: populate data
### Context
After integration, we need to populate the data of fuji markets.

### To do

- [x] Fetch can takes time, therefore display a loader when we don't have data
- [x] Borrow & Collateral
- [x] Chain with the best rate
- [x] APY & APR
- [x] Waterdrop rewards
- [x] Integrated protocol
- [x] Available Liquidity
- [x] When user clicks on a row, he navigate to borrow page with pre filled data

### Explanations

**How to group pairs ?**
Basically, use `sdk.getAllVaultsWithFinancials()` that retrieve a list of vault. Then group vault by pair, and group by chain. Sort by APY.

A row is a Vault and represents a pair. First unfold display this pair on all available chains. Second unfold display the provider available for this vault.

**Borrow & Collateral**
Can be found inside a Vault (`Vault.debt & Vault.collateral`)

**Chain with the best rate**
Simply display the chain with the best borrow APR on this pair

**Supply APY & Borrow APR**
In the response of `sdk.getAllVaultsWithFinancials()`

The waterdrop can be both on Supply APR and Borrow APR.
On hover the waterdrop, display a tooltip with 
```
XX.XX% borrow APR (base) - XX.XX% reward

XX.XX% supply APY (base) - XX.XX% reward
```

**Available Liquidity**
In sdk.getAllVaultsWithFinancials()

**Integrated protocol**
Can be retrieved with `vault.getProviders()`

**User click on row**
Use useStore.changeActiveVault(vault) to set the vault the navigate.

### Related
- ~~APR **waterdrop** will be done on #140~~ moved in this ticket because it's in the response of `sdk.getAllVaultWithFinancials()`
- Saftery ratings will be done on #141
- ~~Available liquidity will be done on #136~~ moved in this ticket because it's in the response of `sdk.getAllVaultWithFinancials()`

### PR DESCRIPTION
**Pull request by Chris-CHEVALIER**
Close #155

### CODE REVIEW

**Comment by brozorec** [comment]
Good job :+1: 

When one hovers over the providers' logos, can we display a tooltip with their names?

Wdyt @Markoyw ?

**Comment by brozorec** [comment]
> Ok so I think this is ready for review, just need help of either @DaigaroCota or @brozorec about navigation after clicking on a Market row.

It has to navigate to "Manage position", ref https://github.com/Fujicracy/fuji-v2/issues/41

**Comment by Markoyw** [comment]
Hey @brozorec @doliG 

1. That's a good idea. I am attaching an example of the tooltip design here
[https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=3042%3A51874&t=bFPZHGdDkTO3x5i9-1]

Also, I'm not sure if we are able to stack the tooltip as such:
Screenshot 2023-01-02 at 8 00 49 PM

2. Ah, it was a comment on the sorting functionality. I was trying to test it - when I click on the header, the arrow changes up to down. However, the data is not sorted.

**Comment by brozorec** [comment]
Awesome, thank you @Markoyw :+1:
Regarding "2." I meant something different: it was about the order of the columns. For the assets' names, we start with the borrowed one while for the rates the supply rate is first.

**Comment by Markoyw** [comment]
@brozorec 

Good point. What do you think if we were to switch the assets column starting from - 'collateral' and then 'borrow'?

**Comment by doliG** [comment]
@Markoyw Design feedbacks on figma are fixed, please check again :)

1. I don't think nested tooltip are a good idea in terms of UX (not mobile friendly) + it's difficult to handle technically, but it's doable. I suggest instead to display one big tooltip with the logo of all protocols and their name.

2. Regarding the column order, I had the same remark as @brozorec and it's an easy change. @Markoyw if you're okay with it I'll do it.

3.Regarding sorting, it's because sorting the data will cause everything to change (even chain with the best rate). @brozorec can we discuss it through a call ? I think it'll be easier.

**Comment by brozorec** [comment]
> @brozorec
> 
> Good point. What do you think if we were to switch the assets column starting from - 'collateral' and then 'borrow'?

@Markoyw Yep, I think it's safe to do so :+1:

**Comment by brozorec** [comment]
1. Initially, we won't have vaults with more than 4 providers, so I suggest we just put a simple tooltip with the names.
2. 
3. Regarding the sorting, I'm creating a ticket for it so that we deal with it later on.

@doliG

**Comment by doliG** [comment]
1. Tooltip done
2. 
3. Ok, I commented the sorting code
4. [NEW] I created #219 that can be done once we have a design. Thanks :)

@brozorec @Markoyw this PR is done, I'm merging it. Thanks for your contributions guys 🔥

**Comment by doliG** [comment]
1. Ok done
2. .
3. I commented the code that sort the table, we'll handle it later
4. [NEW] #219 (waiting for design)

@Markoyw @brozorec I'm merginf this one, thanks you guys for your contributions.

**Pull request merged**
