### PR TITLE
Mobile frontend

### PR DESCRIPTION
**Pull request by ferostar**
Implementation of issue https://github.com/Fujicracy/fuji-v2/issues/394

- [x] Undefined wallet
- [x] Onboarding modal
- [x] Two-row header
- [x] web3-onboard text

*WIP*

### CODE REVIEW

**Comment by ferostar** [comment]
Two quick things I noticed on the `overview` dialog @NikolaiYurchenko :

- Make all top values right-aligned (they’re currently left-aligned)
- LTVProgressBar looks agreat on the desktop, but in the mobile version, the `0% ` green percentage is off, way to the left

**Comment by ferostar** [comment]
I assigned this one to my self so I can't review it 😅

**Comment by brozorec** [comment]
My feedback:
- onboarding modal
- borrow page: in overview, the $ value of borrow amount is always 1$
- reduce height of the second input of the borrow form and make the LTV recommendation fit on one line
image
- round up TVL %
image
- slippage settings don't appear on mobile
- menu: Wallet is stuck to address. What about Transaction history, do we have any designs for it?
image
- when I go to my mobile metamask browser and go to my-postions page, the app craches; not sure how to reproduce or inpsect this

**Comment by ferostar** [comment]
> menu: Wallet is stuck to address. What about Transaction history, do we have any designs for it?

We don't have anything. When the user taps either `Wallet` or `Transaction history`, we just hide the modal. I would remove the transaction history for the time being.

**Comment by ferostar** [comment]
All fixed, can't reproduce the Metamask one -probably because I tested with a wallet with no positions. Shouldn't have anything to do. Still, adding Sentry will help.

Instead of adding a new modal for the account, I simply added the one we already have. Meaning, we now have the transaction list 🥳.

Give it a try @brozorec !

**Review by brozorec — APPROVED** [review]

**Pull request merged**
