### PR TITLE
Fix Liquidation with assets under 18 decimals

### PR DESCRIPTION
**Pull request by pedrovalido**
This PR addresses H-2 in Macro report.

PR to fix the liquidation of assets under 18 decimals. Implemented a test inside the forking tests of liquidation manager. Inside this test, a new vault is deployed with usdc as collateral asset and weth as debt asset (usdc is under 18 decimals). The test follows the same logic as the test_liquidateDefault above implemented for the liquidation manager tests. 
The problem mentioned by macro is the liquidate function inside the borrowing vault not accounting for the assets' decimals when calculating the gained shares which led to full liquidation when the debtAsset had significantly more decimals than the collateral asset. The fix consisted on adding the decimals of collateral to this calculation:

`uint256 gainedAssets = Math.mulDiv(debtToCover, 10 ** _asset.decimals(), discountedPrice);`
`gainedShares = convertToShares(gainedAssets);`

ps.: I think the failing tests on the routers have to do with the "real oracle" branch. This was my bad on #264 and will fix it as mentioned by @DaigaroCota .

### CODE REVIEW

**Comment by DaigaroCota** [comment]
@pedrovalido please confirm if this is ready for review. I believe as you described this branch is based on the mockOracle replacement branch right?

**Comment by pedrovalido** [comment]
You're right Ill move them to the blocked until I fix the real oracle.

**Comment by pedrovalido** [comment]
@DaigaroCota I've fixed the issue with the oracle and if PR has no issues, then this is ready

**Review by DaigaroCota — APPROVED** [review]

**Review by abhishekvispute — COMMENTED** [review]
lgtm

**Pull request merged**
