### PR TITLE
My positions: integration

### LINKED ISSUE #208: My position: integration
### Context

We already started manage position page, but it's good if the user can also have an overview of all his open positions in "My position page"

[> Design](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=509%3A13453&t=kWKXL5FOQSl9ikbs-3)

### Todo

- [x] Integrate the design with hard coded data

### Related

- issue related #41

### PR DESCRIPTION
**Pull request by doliG**
close #208

### CODE REVIEW

**Comment by brozorec** [comment]
1. Make large numbers readable by formatting them according to locale
image

2. Not sure, if it will be handled in this PR, when we click on a row, it navigates to "Manage position"

**Comment by doliG** [comment]
> Make large numbers readable by formatting them according to locale
Will do, although it's more in scope of the logic part but this way I won't forget

> Not sure, if it will be handled in this PR, when we click on a row, it navigates to "Manage position"
Out of scope, do we have a ticket yet for the logic part ? 🤔

**Comment by doliG** [comment]
Hey @Markoyw ,

> Copy change to header: Total Deposits / Total Debt / Available to Borrow / Positions at Risk

Actually we didn't plan the mobile version, and having a big text like "available to borrow" is difficult to handle in that case. My suggestion is to go with a side by side version of this metrics, i.e
```
Total deposits | Total debt
$120,000       | $20,000 
Net APY        | Available to borrow
1.93% <View>   | $60,000 <Borrow>
```

**Comment by doliG** [comment]
Hey @Markoyw, I'm working on your feedbacks.

> Copy change to header: Total Deposits / Total Debt / Available to Borrow / Positions at Risk

Actually we didn't plan the mobile version. My suggestion is to go with a side by side version of this metrics, i.e

But it's not perfect because we have 5 metrics. That's why I suggest to put "position at risk" into a warning box above or below the key metrics. For that we can use https://mui.com/material-ui/react-alert/#basic-alerts

Here's a rough draft of how it looks like:

image



Of course if it does not feel right we can go with another solution, but in any case I need to handle the mobile :)

**Comment by Markoyw** [comment]
Hey @doliG 

I am thinking for the mobile design - we can perhaps leave the 'Positions at Risk' out for now. In any case, the user will still be able to view the liquidation price and close his position if required.

I am attaching the mobile design here 
Screenshot 2023-01-03 at 8 33 00 PM

Figma link to the design:
https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=3095%3A55027&t=rjuor4XEOcsESTMh-1

Cc: @brozorec

**Comment by Markoyw** [comment]
Hi @doliG 

Looks good!

2 minor comments:
1. Change font to 'Inter'
2. Mobile design - to have padding on both sides at 16px for all screens

**Comment by doliG** [comment]
@Markoyw 
1. done
2. done

I'm also merging this one, thanks :)

**Comment by Markoyw** [comment]
@doliG 

Thanks Yome - looks good, all approved!

**Review by Markoyw — COMMENTED** [review]
Reviewed. All approved.

**Pull request merged**
