### PR TITLE
Update frontend assets

### PR DESCRIPTION
**Pull request by ferostar**
From issue https://github.com/Fujicracy/fuji-v2/issues/283

### CODE REVIEW

**Comment by ferostar** [comment]
@brozorec a couple of quick questions:

We have a list of `network` assets. They're

```
Arbitrum
Binance
Ethereum
Fantom
Optimism
Polygon
Potcoin
```

Which ones can we remove for v1?

Also... assets for testnets are duplicated, so we have

```
Optimism Goerli
Goerli
Mumbai
```

as well. I think we should just map testnet icons to the corresponding mainnet, otherwise we'll have duplicated assets without any need.

**Comment by brozorec** [comment]
Sure, let's reuse assets, especially if it's for testnets

**Comment by ferostar** [comment]
@brozorec got it. And what about the networks, can we remove any?

**Comment by brozorec** [comment]
> @brozorec got it. And what about the networks, can we remove any?

Yeah, I don't even know wtf is Potcoin lol

Fantom is not supported by Connext yet but let's keep it, I think they will add it at some point.

**Pull request merged**
