### PR TITLE
Positions summary page functional

### PR DESCRIPTION
**Pull request by DaigaroCota**

### CODE REVIEW

**Comment by brozorec** [comment]
@DaigaroCota great job, so far :+1: I haven't dived into the code but here some preliminary observations:

1. display chain of the position; refer to designs (use the pattern from [here](https://github.com/Fujicracy/fuji-v2/blob/3ebca9f0805510c6c0e56286399d169c3ca31564/packages/frontend/components/Borrow/RouteCard.tsx#L192))
2. display a loader while loading positions similar to the markets page

3. user is on the page but w/o a connected wallet, we need to display a button "Connect Wallet"
4. when the user doesn't have any position, we need to display a placeholder "You don't have open positions yet" and a button "Borrow" 

If 3. and 4. are not in the designs, we have to check with Mark and create a "Design" ticket for it.

**Comment by DaigaroCota** [comment]
> @DaigaroCota great job, so far 👍 I haven't dived into the code but here some preliminary observations:
> 
> 1. display chain of the position; refer to designs (use the pattern from [here](https://github.com/Fujicracy/fuji-v2/blob/3ebca9f0805510c6c0e56286399d169c3ca31564/packages/frontend/components/Borrow/RouteCard.tsx#L192))
> 2. display a loader while loading positions similar to the markets page
> 3. user is on the page but w/o a connected wallet, we need to display a button "Connect Wallet"
> 4. when the user doesn't have any position, we need to display a placeholder "You don't have open positions yet" and a button "Borrow"
> 
> If 3. and 4. are not in the designs, we have to check with Mark and create a "Design" ticket for it.

working on 3. Though I think I would need some guidance. Cases to address are:
1 If no wallet connected show positions tables with message: Please connect wallet.
2 if connected show loader, until positions load.
3 When loaded if positions array has no positions show: No open positions.
4 if loaded and has positions show position rows.
5 If change of wallet go back to line 2.

**Comment by DaigaroCota** [comment]
> > @DaigaroCota great job, so far 👍 I haven't dived into the code but here some preliminary observations:
> > 
> > 1. display chain of the position; refer to designs (use the pattern from [here](https://github.com/Fujicracy/fuji-v2/blob/3ebca9f0805510c6c0e56286399d169c3ca31564/packages/frontend/components/Borrow/RouteCard.tsx#L192))
> > 2. display a loader while loading positions similar to the markets page
> > 3. user is on the page but w/o a connected wallet, we need to display a button "Connect Wallet"
> > 4. when the user doesn't have any position, we need to display a placeholder "You don't have open positions yet" and a button "Borrow"
> > 
> > If 3. and 4. are not in the designs, we have to check with Mark and create a "Design" ticket for it.
> 
> working on 3. Though I think I would need some guidance. Cases to address are: 1 If no wallet connected show positions tables with message: Please connect wallet. 2 if connected show loader, until positions load. 3 When loaded if positions array has no positions show: No open positions. 4 if loaded and has positions show position rows. 5 If change of wallet go back to line 2.

All suggestions [here](https://github.com/Fujicracy/fuji-v2/pull/290#issuecomment-1434304596) have been implemented. @brozorec  this should be ready for review and merge. Thanks @ferostar for the help and contributions.

**Comment by brozorec** [comment]
close #289

**Review by brozorec — APPROVED** [review]

**Comment by brozorec** [comment]
pushed some changes and approved, if it's ok for you, we can merge to main
@DaigaroCota @ferostar

**Pull request merged**
