### PR TITLE
Tablet UI fixes

### PR DESCRIPTION
**Pull request by NikolaiYurchenko**
closes https://github.com/Fujicracy/fuji-v2/issues/468

### CODE REVIEW

**Comment by NikolaiYurchenko** [comment]
@ferostar @brozorec Also changed font style to use local font files again because it is faster

**Comment by NikolaiYurchenko** [comment]
One more point: link tag in head of html still here and next downloads font secont time. Cant figure where it happens yet, worth taking a look later

**Comment by ferostar** [comment]
Just in case @NikolaiYurchenko are all items on the issue done?

**Comment by NikolaiYurchenko** [comment]
@ferostar Yes, it should be

**Review by ferostar — APPROVED** [review]

**Pull request merged**
