### PR TITLE
Connext router bridging slippage

### PR DESCRIPTION
**Pull request by DaigaroCota**

### CODE REVIEW

**Comment by DaigaroCota** [comment]
@brozorec  I did a first "rough" attempt to replace slippage values. As discussed a week ago, I was careless on code optimization. I just wanted to get the idea across. Please let me know what refactor or formatting changes you will suggest. I will also consider additional testing tomorrow. We are getting closer to the finish line. 😀

**Comment by DaigaroCota** [comment]
@ComposableSecurityTeam this is 1/2 missing PRs to complete Audit findings (excluding informational).

**Comment by DaigaroCota** [comment]
I noted the refactor changes and look all good to me. thanks 🙏.

**Comment by brozorec** [comment]
> I noted the refactor changes and look all good to me. thanks pray.

Pushed some other changes too, @DaigaroCota plz review :pray:

**Review by brozorec — APPROVED** [review]
@DaigaroCota the refactoring of the slippage seems good :+1: 
Before merging, can you describe in some comments why we need it and how to use it plz :pray:

**Pull request merged**
